package it.darkroom.timer.assistant.chemistry.inventory;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import it.darkroom.timer.assistant.data.AssistantDatabase;
import it.darkroom.timer.assistant.development.DevelopmentCatalog;

/** R5 — personal chemistry inventory. Catalog source and personal fields are never merged. */
public final class MyChemistryActivity extends Activity {
    private AssistantDatabase db; private LinearLayout list; private int primary,muted,accent;
    private static final String[] CATEGORIES={"rivelatore pellicola","arresto","fissaggio","imbibente","altro"};
    private static final String[] PHYSICAL={"liquido","polvere"};
    private static final String[] SOLUTION={"concentrato","soluzione stock","soluzione di lavoro","monouso","riutilizzabile"};
    private static final String[] UNITS={"ml","litri","g"};

    @Override protected void onCreate(Bundle b){super.onCreate(b);palette();db=new AssistantDatabase(this);build();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){if(db!=null)db.close();super.onDestroy();}
    private void palette(){boolean dark=getSharedPreferences("ui",MODE_PRIVATE).getBoolean("darkroomMode",false);primary=dark?Color.rgb(255,42,42):Color.rgb(238,240,242);muted=dark?Color.rgb(145,34,34):Color.rgb(145,151,158);accent=dark?Color.rgb(255,42,42):Color.rgb(197,54,58);}

    private void build(){ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.BLACK);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(16),dp(18),dp(28));s.addView(root);TextView t=text("LA MIA CHIMICA",25,primary,true);t.setGravity(Gravity.CENTER);root.addView(t);TextView sub=text("Inventario personale · dati fonte separati dai dati dell'utente",12,muted,false);sub.setGravity(Gravity.CENTER);sub.setPadding(0,dp(4),0,dp(14));root.addView(sub);
        Button catalog=button("AGGIUNGI ALLA MIA CHIMICA · DAL CATALOGO");catalog.setOnClickListener(v->catalogDialog());root.addView(catalog,margin(-1,dp(58),0,0,0,dp(8)));
        Button manual=button("AGGIUNGI PRODOTTO MANUALMENTE");manual.setOnClickListener(v->manualDialog());root.addView(manual,margin(-1,dp(58),0,0,0,dp(14)));
        list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);Button back=button("← ASSISTANT");back.setOnClickListener(v->finish());root.addView(back);setContentView(s);refresh();}

    private void catalogDialog(){LinearLayout box=form();EditText developer=field("Nome rivelatore esatto dal catalogo");EditText maker=field("Produttore (dato personale descrittivo)");EditText amount=decimal("Quantità iniziale");Spinner unit=spinner(UNITS);Spinner solution=spinner(SOLUTION);EditText opened=field("Data apertura (opzionale)");EditText storage=field("Posizione / conservazione (opzionale)");EditText notes=field("Note personali");for(android.view.View x:new android.view.View[]{developer,maker,amount,unit,solution,opened,storage,notes})box.addView(x);
        new AlertDialog.Builder(this).setTitle("AGGIUNGI DAL CATALOGO").setMessage("Il prodotto deve esistere nel catalogo sviluppo. Le sole diluizioni mostrate/salvate saranno quelle presenti nei dati sorgente.").setView(box).setPositiveButton("AGGIUNGI",(d,w)->{String name=developer.getText().toString().trim();String[] dil=DevelopmentCatalog.developerDilutions(name);if(dil==null||dil.length==0){toast("Prodotto non trovato nel catalogo: usa AGGIUNGI PRODOTTO MANUALMENTE.");return;}double q=parseDouble(amount.getText().toString(),Double.NaN);if(!(q>=0)){toast("Quantità non valida");return;}AssistantDatabase.ChemicalItem x=new AssistantDatabase.ChemicalItem();x.sourceType=AssistantDatabase.SOURCE_CATALOG;x.sourceProductKey=name.toLowerCase(Locale.ITALY);x.manufacturer=maker.getText().toString();x.name=name;x.category="rivelatore pellicola";x.physicalState="liquido";x.solutionType=(String)solution.getSelectedItem();x.initialAmount=q;x.remainingAmount=q;x.unit=(String)unit.getSelectedItem();x.openDate=opened.getText().toString();x.storage=storage.getText().toString();x.notes=notes.getText().toString();x.documentedDilutions=join(dil);x.sourceName="DevelopmentCatalog";x.dataType="DATI FONTE / CATALOGO";x.personalDilution="";db.saveChemical(x);toast("Prodotto aggiunto a LA MIA CHIMICA");refresh();}).setNegativeButton("ANNULLA",null).show();}

    private void manualDialog(){LinearLayout box=form();EditText maker=field("Produttore");EditText name=field("Nome prodotto");Spinner category=spinner(CATEGORIES);Spinner physical=spinner(PHYSICAL);Spinner solution=spinner(SOLUTION);EditText amount=decimal("Quantità iniziale");Spinner unit=spinner(UNITS);EditText dilution=field("DILUIZIONE PERSONALE (opzionale)");EditText purchase=field("Data acquisto (opzionale)");EditText opened=field("Data apertura (opzionale)");EditText prepared=field("Data preparazione (opzionale)");EditText expiry=field("Scadenza dichiarata (opzionale)");EditText storage=field("Posizione / conservazione (opzionale)");EditText notes=field("Note personali");for(android.view.View x:new android.view.View[]{maker,name,category,physical,solution,amount,unit,dilution,purchase,opened,prepared,expiry,storage,notes})box.addView(x);
        new AlertDialog.Builder(this).setTitle("AGGIUNGI PRODOTTO MANUALMENTE").setMessage("PRODOTTO PERSONALE / DATI INSERITI DALL'UTENTE. Nessuna diluizione o capacità sarà presentata come ufficiale.").setView(box).setPositiveButton("SALVA",(d,w)->{if(name.getText().toString().trim().isEmpty()){toast("Inserisci il nome prodotto");return;}double q=parseDouble(amount.getText().toString(),Double.NaN);if(!(q>=0)){toast("Quantità non valida");return;}AssistantDatabase.ChemicalItem x=new AssistantDatabase.ChemicalItem();x.sourceType=AssistantDatabase.SOURCE_USER;x.manufacturer=maker.getText().toString();x.name=name.getText().toString().trim();x.category=(String)category.getSelectedItem();x.physicalState=(String)physical.getSelectedItem();x.solutionType=(String)solution.getSelectedItem();x.initialAmount=q;x.remainingAmount=q;x.unit=(String)unit.getSelectedItem();x.personalDilution=dilution.getText().toString();x.purchaseDate=purchase.getText().toString();x.openDate=opened.getText().toString();x.preparedDate=prepared.getText().toString();x.expiryDate=expiry.getText().toString();x.storage=storage.getText().toString();x.notes=notes.getText().toString();x.dataType="PRODOTTO PERSONALE / DATI INSERITI DALL'UTENTE";x.sourceName="Utente";db.saveChemical(x);toast("Prodotto personale salvato");refresh();}).setNegativeButton("ANNULLA",null).show();}

    private void refresh(){if(list==null)return;list.removeAllViews();List<AssistantDatabase.ChemicalItem> items=db.listChemicals(true);if(items.isEmpty()){TextView e=text("Nessun prodotto nell'inventario.",14,muted,false);e.setPadding(0,dp(20),0,dp(20));list.addView(e);return;}for(AssistantDatabase.ChemicalItem x:items){String label=x.name+" · "+fmtQty(x.remainingAmount,x.unit)+" · "+x.status();Button b=button(label);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setOnClickListener(v->detail(x.id));list.addView(b,margin(-1,dp(72),0,0,0,dp(8)));}}

    private void detail(long id){AssistantDatabase.ChemicalItem x=db.getChemical(id);if(x==null)return;String source=AssistantDatabase.SOURCE_USER.equals(x.sourceType)?"PRODOTTO PERSONALE / DATI INSERITI DALL'UTENTE":"DATI FONTE";String dil=AssistantDatabase.SOURCE_USER.equals(x.sourceType)?labelValue("Diluizione personale",x.personalDilution):labelValue("Diluizioni documentate",x.documentedDilutions);String capacity=x.capacitySource==null||x.capacitySource.trim().isEmpty()?"CAPACITÀ NON DOCUMENTATA":fmt(x.capacityValue)+" "+x.capacityUnit+" · "+x.capacitySource;String msg=source+"\n"+labelValue("Produttore",x.manufacturer)+labelValue("Prodotto",x.name)+dil+labelValue("Fonte",x.sourceName)+"\nDATI PERSONALI\n"+labelValue("Categoria",x.category)+labelValue("Stato fisico",x.physicalState)+labelValue("Tipo",x.solutionType)+labelValue("Quantità iniziale",fmtQty(x.initialAmount,x.unit))+labelValue("Quantità residua",fmtQty(x.remainingAmount,x.unit))+labelValue("Stato",x.status())+labelValue("Acquisto",x.purchaseDate)+labelValue("Apertura",x.openDate)+labelValue("Preparazione",x.preparedDate)+labelValue("Scadenza dichiarata",x.expiryDate)+labelValue("Conservazione",x.storage)+labelValue("Note",x.notes)+"\n"+capacity;
        new AlertDialog.Builder(this).setTitle(x.name).setMessage(msg).setPositiveButton("AZIONI",(d,w)->actions(id)).setNegativeButton("CHIUDI",null).show();}

    private void actions(long id){String[] a={"AGGIORNA QUANTITÀ RESIDUA","STORICO UTILIZZI","ARCHIVIA / RIPRISTINA"};new AlertDialog.Builder(this).setTitle("Azioni chimica").setItems(a,(d,w)->{if(w==0)remainingDialog(id);else if(w==1)usageHistory(id);else archiveToggle(id);}).show();}
    private void remainingDialog(long id){AssistantDatabase.ChemicalItem x=db.getChemical(id);if(x==null)return;EditText q=decimal("Quantità residua "+x.unit);q.setText(fmt(x.remainingAmount));new AlertDialog.Builder(this).setTitle("AGGIORNA QUANTITÀ RESIDUA").setMessage("La modifica non altera retroattivamente lo storico utilizzi.").setView(q).setPositiveButton("SALVA",(d,w)->{double v=parseDouble(q.getText().toString(),Double.NaN);if(!(v>=0)){toast("Quantità non valida");return;}x.remainingAmount=v;db.updateChemical(x);refresh();}).setNegativeButton("ANNULLA",null).show();}
    private void archiveToggle(long id){AssistantDatabase.ChemicalItem x=db.getChemical(id);if(x==null)return;x.archived=!x.archived;db.updateChemical(x);toast(x.archived?"Prodotto archiviato":"Prodotto ripristinato");refresh();}
    private void usageHistory(long id){List<AssistantDatabase.ChemicalUsage> rows=db.listChemicalUsage(id);StringBuilder b=new StringBuilder();if(rows.isEmpty())b.append("Nessun utilizzo registrato.");for(AssistantDatabase.ChemicalUsage u:rows){b.append(date(u.createdAt)).append("\n").append(u.film).append(" · ").append(u.format).append(" · ").append(u.rolls).append(" rulli\n").append("Usati: ").append(fmtQty(u.quantityUsed,u.unit)).append(" · Residuo: ").append(fmtQty(u.remainingAfter,u.unit));if(!u.note.isEmpty())b.append("\n").append(u.note);b.append("\n\n");}new AlertDialog.Builder(this).setTitle("STORICO UTILIZZI CHIMICA").setMessage(b.toString()).setPositiveButton("CHIUDI",null).show();}

    private static String join(String[] x){StringBuilder b=new StringBuilder();for(String s:x){if(s==null||s.trim().isEmpty())continue;if(b.length()>0)b.append(", ");b.append(s.trim());}return b.toString();}private String labelValue(String k,String v){return k+": "+empty(v)+"\n";}private static String empty(String s){return s==null||s.trim().isEmpty()?"—":s;}private static String fmt(double v){return Math.abs(v-Math.rint(v))<.05?String.format(Locale.ITALY,"%.0f",v):String.format(Locale.ITALY,"%.1f",v);}private static String fmtQty(double v,String u){return fmt(v)+" "+(u==null?"":u);}private static String date(long ms){return DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT,Locale.ITALY).format(new Date(ms));}
    private LinearLayout form(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),0,dp(18),0);return b;}private EditText field(String h){EditText x=new EditText(this);x.setHint(h);x.setHintTextColor(muted);x.setTextColor(primary);return x;}private EditText decimal(String h){EditText x=field(h);x.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return x;}private Spinner spinner(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(primary);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private LinearLayout.LayoutParams margin(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private double parseDouble(String s,double d){try{return Double.parseDouble(s.trim().replace(',','.'));}catch(Exception e){return d;}}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
