plugins {
    id 'com.android.application'
}

android {
    namespace 'it.darkroom.assistant'
    compileSdk 34

    defaultConfig {
        applicationId 'it.darkroom.assistant.app'
        minSdk 26
        targetSdk 34
        versionCode 14
        versionName '0.3.0'
    }

    signingConfigs {
        release {
            storeFile file(System.getenv('ANDROID_KEYSTORE_FILE'))
            storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
            keyAlias System.getenv('ANDROID_KEY_ALIAS')
            keyPassword System.getenv('ANDROID_KEY_PASSWORD')
            enableV1Signing true
            enableV2Signing true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
}
