from pathlib import Path
root=Path('combined/src/main/java/it/darkroom/timer'); main=root/'MainActivity.java'; s=main.read_text(encoding='utf-8')
a='    private LinearLayout buildPrintPanel() {\n        LinearLayout box = card();'; b='    private LinearLayout buildPrintPanel() {\n        LinearLayout box = card();\n        Button resizePrint = compactButton("RIDIMENSIONA STAMPA");\n        resizePrint.setOnClickListener(v -> startActivity(new Intent(this, EnlargementActivity.class).putExtra("mode", "resize")));\n        box.addView(resizePrint, margin(lp(-1, dp(46)), 0, 0, 0, 10));'
if a not in s: raise SystemExit('print marker missing'); s=s.replace(a,b,1)
a='    private LinearLayout buildTestPanel() {\n        LinearLayout outer = new LinearLayout(this);\n        outer.setOrientation(LinearLayout.VERTICAL);'; b='    private LinearLayout buildTestPanel() {\n        LinearLayout outer = new LinearLayout(this);\n        outer.setOrientation(LinearLayout.VERTICAL);\n        Button setEnlargement = compactButton("IMPOSTA INGRANDIMENTO");\n        setEnlargement.setOnClickListener(v -> startActivity(new Intent(this, EnlargementActivity.class).putExtra("mode", "setup")));\n        outer.addView(setEnlargement, margin(lp(-1, dp(46)), 0, 0, 0, 10));'
if a not in s: raise SystemExit('test marker missing'); s=s.replace(a,b,1); main.write_text(s,encoding='utf-8')
java=r'''package it.darkroom.timer;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;
public final class EnlargementActivity extends Activity {
 static final double[][] C80={{1,6},{1.5,7},{2,10},{2.5,13},{3,17},{3.5,20},{4,24},{5,32},{6,40},{7,48},{7.6,53}};
 static final double[][] C50={{2.5,1},{3,2},{3.5,4},{4,6},{5,11},{6,16},{7,21},{7.6,24},{9,32},{10,37},{11,42},{13,52}};
 EditText w,h;Spinner neg,fill;TextView out;String mode;int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}TextView t(String x,int z){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(0,dp(6),0,dp(6));return v;}
 public void onCreate(Bundle b){super.onCreate(b);mode=getIntent().getStringExtra("mode");if(mode==null)mode="setup";ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(20),dp(24),dp(20),dp(28));r.setBackgroundColor(Color.BLACK);sc.addView(r);r.addView(t("resize".equals(mode)?"RIDIMENSIONA STAMPA":"IMPOSTA INGRANDIMENTO",24));r.addView(t("Calibrato per Meopta Opemus 6 — obiettivi 50/80 mm",12));neg=new Spinner(this);neg.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"35 mm — 50 mm","6×6 — 80 mm"}));r.addView(t("NEGATIVO",13));r.addView(neg);w=new EditText(this);h=new EditText(this);w.setHint("Larghezza carta cm");h.setHint("Altezza carta cm");w.setInputType(2|8192);h.setInputType(2|8192);w.setTextColor(Color.WHITE);h.setTextColor(Color.WHITE);w.setHintTextColor(Color.GRAY);h.setHintTextColor(Color.GRAY);r.addView(w);r.addView(h);fill=new Spinner(this);fill.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"IMMAGINE INTERA","RIEMPI LARGHEZZA","RIEMPI ALTEZZA"}));r.addView(fill);Button c=new Button(this);c.setText("CALCOLA");c.setOnClickListener(v->calc());r.addView(c);out=t("",16);r.addView(out);setContentView(sc);}
 static double b2c(double b,double[][]t){if(b<t[0][0]||b>t[t.length-1][0])return Double.NaN;for(int i=0;i<t.length-1;i++)if(b>=t[i][0]&&b<=t[i+1][0]){double q=(b-t[i][0])/(t[i+1][0]-t[i][0]);return t[i][1]+q*(t[i+1][1]-t[i][1]);}return t[t.length-1][1];}
 static double c2b(double c,double[][]t){if(c<t[0][1]||c>t[t.length-1][1])return Double.NaN;for(int i=0;i<t.length-1;i++)if(c>=t[i][1]&&c<=t[i+1][1]){double q=(c-t[i][1])/(t[i+1][1]-t[i][1]);return t[i][0]+q*(t[i+1][0]-t[i][0]);}return t[t.length-1][0];}
 static int snap(double ms){return(int)Math.round(ms/500.0)*500;}static String val(String m,String k){for(String x:m.split("\\|"))if(x.startsWith(k+"="))return x.substring(k.length()+1);return"";}static double num(String m,String k){try{return Double.parseDouble(val(m,k));}catch(Exception e){return Double.NaN;}}
 void calc(){try{double W=Double.parseDouble(w.getText().toString().replace(',','.'))*10,H=Double.parseDouble(h.getText().toString().replace(',','.'))*10;boolean a=neg.getSelectedItemPosition()==0;double nw=a?36:56,nh=a?24:56,b=fill.getSelectedItemPosition()==1?W/nw:fill.getSelectedItemPosition()==2?H/nh:Math.min(W/nw,H/nh),c=b2c(b,a?C50:C80);if(Double.isNaN(c)){out.setText("FORMATO FUORI DALL'INTERVALLO CALIBRATO");return;}double pw=b*nw/10,ph=b*nh/10,rw=Math.min(W,b*nw)/10,rh=Math.min(H,b*nh)/10;String crop=(pw>W/10+.001||ph>H/10+.001)?"SÌ":"NO";String sum=String.format(Locale.ITALY,"β %.3f\nColonna teorica %.2f\nImmagine proiettata %.1f × %.1f cm\nRegistrata sulla carta %.1f × %.1f cm\nCrop: %s",b,c,pw,ph,rw,rh,crop);if("setup".equals(mode)){save(a,W,H,b,c,pw,ph,crop);out.setText(sum+"\n\nRegistrato nella ricetta corrente.");}else resize(a,W,H,b,c,pw,ph,crop,sum);}catch(Exception e){out.setText("Inserisci dimensioni carta valide.");}}
 void save(boolean a,double W,double H,double b,double c,double pw,double ph,String crop){String m=String.format(Locale.US,"neg=%s|lens=%d|paper=%.1fx%.1f|fill=%d|beta=%.8f|col=%.8f|proj=%.2fx%.2f|crop=%s",a?"35":"66",a?50:80,W/10,H/10,fill.getSelectedItemPosition(),b,c,pw,ph,crop);getSharedPreferences("ui",0).edit().putString("enlargementMeta",m).putString("enlargementLastLog","IMPOSTA INGRANDIMENTO · "+m).apply();}
 void resize(boolean a,double W,double H,double b2,double c2,double pw,double ph,String crop,String sum){SharedPreferences p=getSharedPreferences("ui",0);String old=p.getString("enlargementMeta","");double b1=num(old,"beta"),c1=num(old,"col");if(Double.isNaN(b1)){out.setText("Manca l'ingrandimento iniziale nella ricetta. Usa prima IMPOSTA INGRANDIMENTO.");return;}if((a&&!"35".equals(val(old,"neg")))||(!a&&!"66".equals(val(old,"neg")))){out.setText("COMPENSAZIONE NON CONSENTITA: 50 mm ↔ 80 mm.");return;}double f=Math.pow((b2+1)/(b1+1),2),st=Math.log(f)/Math.log(2);int ob=p.getInt("printWidthMs",8500),nb=snap(ob*f);String msg=sum+String.format(Locale.ITALY,"\n\nβ iniziale %.3f → β finale %.3f\nColonna %.2f → %.2f\nFattore ×%.2f\nVariazione %+.2f stop\nTempo %.1f s → %.1f s",b1,b2,c1,c2,f,st,ob/1000.,nb/1000.);out.setText(msg);new AlertDialog.Builder(this).setTitle("NUOVA RICETTA DERIVATA").setMessage(msg).setNegativeButton("ANNULLA",null).setPositiveButton("CREA",(d,x)->derive(p,a,W,H,b1,b2,c1,c2,f,st,pw,ph,crop)).show();}
 void derive(SharedPreferences p,boolean a,double W,double H,double b1,double b2,double c1,double c2,double f,double st,double pw,double ph,String crop){String or=p.getString("exposureRecipe",""),os=p.getString("printSequence","");int ob=p.getInt("printWidthMs",8500);ExposureRecipe r=ExposureRecipe.decode(or);PrintSequence q=PrintSequence.decode(os);int nb=snap(ob*f);if(r.originalBaseMs>0)r.originalBaseMs=snap(r.originalBaseMs*f);r.operationalBaseMs=snap((r.operationalBaseMs>0?r.operationalBaseMs:ob)*f);if(q.hasSplit()){q.split.softMs=snap(q.split.softMs*f);q.split.hardMs=snap(q.split.hardMs*f);}for(PrintCorrection c:q.corrections)if(c!=null&&c.milliseconds>0)c.milliseconds=snap(c.milliseconds*f);String oldPaper=val(p.getString("enlargementMeta",""),"paper"),newPaper=String.format(Locale.ITALY,"%.1fx%.1f",W/10,H/10),note=String.format(Locale.ITALY,"Derivata da ricetta %s → %s · compensazione %+.2f stop · fattore ×%.2f",oldPaper,newPaper,st,f);String nm=String.format(Locale.US,"neg=%s|lens=%d|paper=%.1fx%.1f|fill=%d|beta=%.8f|col=%.8f|proj=%.2fx%.2f|crop=%s",a?"35":"66",a?50:80,W/10,H/10,fill.getSelectedItemPosition(),b2,c2,pw,ph,crop);String hist=p.getString("enlargementDerivedRecipes","")+"\nORIGIN{"+or+"} SEQ{"+os+"} -> NEW{"+r.encode()+"} SEQ{"+q.encode()+"} b1="+b1+" b2="+b2+" c1="+c1+" c2="+c2+" factor="+f+" stops="+st+" "+note;p.edit().putString("enlargementDerivedRecipes",hist).putString("exposureRecipe",r.encode()).putString("printSequence",q.encode()).putInt("printWidthMs",nb).putString("enlargementMeta",nm).putString("enlargementLastLog",note).apply();Toast.makeText(this,"Ricetta derivata creata · tempi a 0,5 s",Toast.LENGTH_LONG).show();out.append("\n\n"+note);}
}'''
(root/'EnlargementActivity.java').write_text(java,encoding='utf-8')
mp=Path('combined/src/main/AndroidManifest.xml');m=mp.read_text(encoding='utf-8');needle='        <activity\n            android:name=".MainActivity"';repl='        <activity android:name=".EnlargementActivity" android:screenOrientation="portrait" android:exported="false" />\n\n'+needle
if needle not in m:raise SystemExit('manifest marker missing')
mp.write_text(m.replace(needle,repl,1),encoding='utf-8')
print('v016 enlargement patch applied')
