from pathlib import Path
root=Path('combined/src/main/java/it/darkroom/timer')
main=root/'MainActivity.java'
s=main.read_text(encoding='utf-8')
# Reload the derived recipe immediately when returning from enlargement.
needle='    @Override protected void onResume() {\n        super.onResume();'
repl='    @Override protected void onResume() {\n        super.onResume();\n        SharedPreferences ep = getSharedPreferences("ui", MODE_PRIVATE);\n        if (ep.getBoolean("enlargementReloadPending", false)) {\n            ep.edit().remove("enlargementReloadPending").apply();\n            printWidthMs = ep.getInt("printWidthMs", printWidthMs);\n            exposureRecipe = ExposureRecipe.decode(ep.getString("exposureRecipe", ""));\n            printSequence = PrintSequence.decode(ep.getString("printSequence", ""));\n            recreate();\n            return;\n        }'
if needle not in s: raise SystemExit('onResume marker missing')
s=s.replace(needle,repl,1)
# Make resize available from LOG too and surface enlargement log metadata.
needle='    private LinearLayout buildLogPanel() {'
if needle not in s: raise SystemExit('buildLogPanel marker missing')
repl=needle+'\n        LinearLayout enlargementLogBox = card();\n        Button resizeSaved = compactButton("RIDIMENSIONA STAMPA");\n        resizeSaved.setOnClickListener(v -> startActivity(new Intent(this, EnlargementActivity.class).putExtra("mode", "resize")));\n        enlargementLogBox.addView(resizeSaved, margin(lp(-1, dp(46)), 0, 0, 0, 8));\n        String enlargementNote = getSharedPreferences("ui", MODE_PRIVATE).getString("enlargementLastLog", "");\n        if (!enlargementNote.isEmpty()) enlargementLogBox.addView(text(enlargementNote, 12, MUTED, false));'
s=s.replace(needle,repl,1)
# Ensure the returned log panel contains the enlargement box, regardless of its local variable name.
marker='        LinearLayout logPanel = new LinearLayout(this);'
if marker in s:
    s=s.replace(marker,marker+'\n        logPanel.addView(enlargementLogBox, margin(lp(-1,-2),0,0,0,10));',1)
else:
    # fallback: first vertical container created in buildLogPanel
    pos=s.index('    private LinearLayout buildLogPanel() {')
    end=s.index('\n    private ',pos+10)
    seg=s[pos:end]
    target='        LinearLayout outer = new LinearLayout(this);'
    if target in seg:
        seg=seg.replace(target,target+'\n        outer.addView(enlargementLogBox, margin(lp(-1,-2),0,0,0,10));',1)
        s=s[:pos]+seg+s[end:]
main.write_text(s,encoding='utf-8')

java=r'''package it.darkroom.timer;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;
public final class EnlargementActivity extends Activity {
 static final double[][] C80={{1,6},{1.5,7},{2,10},{2.5,13},{3,17},{3.5,20},{4,24},{5,32},{6,40},{7,48},{7.6,53}};
 static final double[][] C50={{2.5,1},{3,2},{3.5,4},{4,6},{5,11},{6,16},{7,21},{7.6,24},{9,32},{10,37},{11,42},{13,52}};
 static final String[] PAPERS={"Foma 8,9 × 12,7","Foma 10,5 × 14,8","Foma 12,7 × 17,8 (13×18)","Foma 17,8 × 24,0 (18×24)","Foma 20,3 × 25,4","Foma 24,0 × 30,5 (24×30)","Foma 27,9 × 35,6","Foma 30,5 × 40,6 (30×40)","Foma 40,6 × 50,8 (40×50)","Foma 50,8 × 61,0 (50×60)","PERSONALIZZATO"};
 static final double[][] PD={{8.9,12.7},{10.5,14.8},{12.7,17.8},{17.8,24.0},{20.3,25.4},{24.0,30.5},{27.9,35.6},{30.5,40.6},{40.6,50.8},{50.8,61.0}};
 EditText w,h; Spinner neg,fill,paper; TextView out; String mode; SharedPreferences p;
 int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(72,72,72));return g;} TextView t(String x,int z){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(0,dp(6),0,dp(6));return v;} Button b(String x){Button v=new Button(this);v.setText(x);v.setTextColor(Color.WHITE);v.setBackground(bg(Color.rgb(42,42,42),10));return v;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("ui",0);mode=getIntent().getStringExtra("mode");if(mode==null)mode="setup";ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(14),dp(18),dp(30));r.setBackgroundColor(Color.BLACK);sc.addView(r);Button back=b("←  INDIETRO");back.setOnClickListener(v->finish());r.addView(back,new LinearLayout.LayoutParams(-1,dp(46)));r.addView(t("resize".equals(mode)?"RIDIMENSIONA STAMPA":"IMPOSTA INGRANDIMENTO",24));r.addView(t("Calibrato per Meopta Opemus 6 — obiettivi 50/80 mm",12));neg=new Spinner(this);neg.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"35 mm — 50 mm","6×6 — 80 mm"}));r.addView(t("NEGATIVO",13));r.addView(neg);paper=new Spinner(this);paper.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,PAPERS));r.addView(t("FORMATO CARTA FOMA",13));r.addView(paper);w=new EditText(this);h=new EditText(this);w.setHint("Larghezza carta cm");h.setHint("Altezza carta cm");w.setInputType(2|8192);h.setInputType(2|8192);w.setTextColor(Color.WHITE);h.setTextColor(Color.WHITE);w.setHintTextColor(Color.GRAY);h.setHintTextColor(Color.GRAY);r.addView(w);r.addView(h);Button rotate=b("↔ INVERTI LARGHEZZA / ALTEZZA");rotate.setOnClickListener(v->{String x=w.getText().toString();w.setText(h.getText().toString());h.setText(x);});r.addView(rotate,new LinearLayout.LayoutParams(-1,dp(46)));fill=new Spinner(this);fill.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"IMMAGINE INTERA","RIEMPI LARGHEZZA","RIEMPI ALTEZZA"}));r.addView(t("MODALITÀ",13));r.addView(fill);Button c=b("CALCOLA");c.setOnClickListener(v->calc());r.addView(c,new LinearLayout.LayoutParams(-1,dp(52)));out=t("",16);r.addView(out);paper.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>a){}public void onItemSelected(android.widget.AdapterView<?>a,View v,int pos,long id){if(pos<PD.length){w.setText(fmt(PD[pos][0]));h.setText(fmt(PD[pos][1]));w.setEnabled(false);h.setEnabled(false);}else{w.setEnabled(true);h.setEnabled(true);}}});restore();setContentView(sc);}
 String fmt(double x){return String.format(Locale.ITALY,"%.1f",x);} void restore(){neg.setSelection(p.getInt("enlargementUiNeg",0));fill.setSelection(p.getInt("enlargementUiFill",0));int pi=p.getInt("enlargementUiPaper",2);paper.setSelection(pi);if(pi>=PD.length){w.setText(p.getString("enlargementUiW",""));h.setText(p.getString("enlargementUiH",""));}String last=p.getString("enlargementUiResult","");if(!last.isEmpty())out.setText(last);} void saveUi(String result){p.edit().putInt("enlargementUiNeg",neg.getSelectedItemPosition()).putInt("enlargementUiFill",fill.getSelectedItemPosition()).putInt("enlargementUiPaper",paper.getSelectedItemPosition()).putString("enlargementUiW",w.getText().toString()).putString("enlargementUiH",h.getText().toString()).putString("enlargementUiResult",result).apply();}
 protected void onPause(){super.onPause();saveUi(out.getText().toString());}
 static double b2c(double b,double[][]t){if(b<t[0][0]||b>t[t.length-1][0])return Double.NaN;for(int i=0;i<t.length-1;i++)if(b>=t[i][0]&&b<=t[i+1][0]){double q=(b-t[i][0])/(t[i+1][0]-t[i][0]);return t[i][1]+q*(t[i+1][1]-t[i][1]);}return t[t.length-1][1];} static int snap(double ms){return(int)Math.round(ms/500.0)*500;} static String val(String m,String k){for(String x:m.split("\\|"))if(x.startsWith(k+"="))return x.substring(k.length()+1);return"";} static double num(String m,String k){try{return Double.parseDouble(val(m,k));}catch(Exception e){return Double.NaN;}}
 void calc(){try{double W=Double.parseDouble(w.getText().toString().replace(',','.'))*10,H=Double.parseDouble(h.getText().toString().replace(',','.'))*10;boolean a=neg.getSelectedItemPosition()==0;double nw=a?36:56,nh=a?24:56,beta=fill.getSelectedItemPosition()==1?W/nw:fill.getSelectedItemPosition()==2?H/nh:Math.min(W/nw,H/nh),col=b2c(beta,a?C50:C80);if(Double.isNaN(col)){out.setText("FORMATO FUORI DALL'INTERVALLO CALIBRATO");saveUi(out.getText().toString());return;}double pw=beta*nw/10,ph=beta*nh/10;String crop=(pw>W/10+.001||ph>H/10+.001)?"SÌ":"NO";String sum=String.format(Locale.ITALY,"β %.3f\nColonna teorica %.2f\nImmagine proiettata %.1f × %.1f cm\nCrop: %s",beta,col,pw,ph,crop);if("setup".equals(mode)){saveMeta(a,W,H,beta,col,pw,ph,crop);out.setText(sum+"\n\nRegistrato nella ricetta corrente.");saveUi(out.getText().toString());}else resize(a,W,H,beta,col,pw,ph,crop,sum);}catch(Exception e){out.setText("Inserisci dimensioni carta valide.");}}
 void saveMeta(boolean a,double W,double H,double beta,double col,double pw,double ph,String crop){String m=String.format(Locale.US,"neg=%s|lens=%d|paper=%.1fx%.1f|fill=%d|beta=%.8f|col=%.8f|proj=%.2fx%.2f|crop=%s",a?"35":"66",a?50:80,W/10,H/10,fill.getSelectedItemPosition(),beta,col,pw,ph,crop);p.edit().putString("enlargementMeta",m).putString("enlargementLastLog","IMPOSTA INGRANDIMENTO · "+m).apply();}
 void resize(boolean a,double W,double H,double b2,double c2,double pw,double ph,String crop,String sum){String old=p.getString("enlargementMeta","");double b1=num(old,"beta"),c1=num(old,"col");if(Double.isNaN(b1)){out.setText("Manca l'ingrandimento iniziale nella ricetta. Usa prima IMPOSTA INGRANDIMENTO.");return;}if((a&&!"35".equals(val(old,"neg")))||(!a&&!"66".equals(val(old,"neg")))){out.setText("COMPENSAZIONE NON CONSENTITA: 50 mm ↔ 80 mm.");return;}double f=Math.pow((b2+1)/(b1+1),2),st=Math.log(f)/Math.log(2);int ob=p.getInt("printWidthMs",8500),nb=snap(ob*f);String msg=sum+String.format(Locale.ITALY,"\n\nβ iniziale %.3f → β finale %.3f\nColonna %.2f → %.2f\nFattore ×%.2f\nVariazione %+.2f stop\nTempo %.1f s → %.1f s",b1,b2,c1,c2,f,st,ob/1000.,nb/1000.);out.setText(msg);saveUi(msg);confirmDerived(msg,()->derive(a,W,H,b1,b2,c1,c2,f,st,pw,ph,crop));}
 void confirmDerived(String msg,final Runnable yes){final Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout q=new LinearLayout(this);q.setOrientation(LinearLayout.VERTICAL);q.setPadding(dp(18),dp(16),dp(18),dp(18));q.setBackground(bg(Color.rgb(24,24,24),14));TextView title=t("NUOVA RICETTA DERIVATA",20);q.addView(title);q.addView(t(msg,14));Button ok=b("CREA");Button no=b("ANNULLA");ok.setOnClickListener(v->{d.dismiss();yes.run();});no.setOnClickListener(v->d.dismiss());q.addView(ok,new LinearLayout.LayoutParams(-1,dp(50)));q.addView(no,new LinearLayout.LayoutParams(-1,dp(46)));d.setContentView(q);d.show();Window ww=d.getWindow();if(ww!=null){ww.setBackgroundDrawableResource(android.R.color.transparent);ww.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94f),ViewGroup.LayoutParams.WRAP_CONTENT);}}
 void derive(boolean a,double W,double H,double b1,double b2,double c1,double c2,double f,double st,double pw,double ph,String crop){String or=p.getString("exposureRecipe",""),os=p.getString("printSequence","");int ob=p.getInt("printWidthMs",8500);ExposureRecipe r=ExposureRecipe.decode(or);PrintSequence q=PrintSequence.decode(os);int nb=snap(ob*f);if(r.originalBaseMs>0)r.originalBaseMs=snap(r.originalBaseMs*f);r.operationalBaseMs=snap((r.operationalBaseMs>0?r.operationalBaseMs:ob)*f);if(q.hasSplit()){q.split.softMs=snap(q.split.softMs*f);q.split.hardMs=snap(q.split.hardMs*f);}for(PrintCorrection c:q.corrections)if(c!=null&&c.milliseconds>0)c.milliseconds=snap(c.milliseconds*f);String oldPaper=val(p.getString("enlargementMeta",""),"paper"),newPaper=String.format(Locale.ITALY,"%.1fx%.1f",W/10,H/10),note=String.format(Locale.ITALY,"Derivata da ricetta %s → %s · compensazione %+.2f stop · fattore ×%.2f",oldPaper,newPaper,st,f);String nm=String.format(Locale.US,"neg=%s|lens=%d|paper=%.1fx%.1f|fill=%d|beta=%.8f|col=%.8f|proj=%.2fx%.2f|crop=%s",a?"35":"66",a?50:80,W/10,H/10,fill.getSelectedItemPosition(),b2,c2,pw,ph,crop);String hist=p.getString("enlargementDerivedRecipes","")+"\nORIGIN{"+or+"} SEQ{"+os+"} -> NEW{"+r.encode()+"} SEQ{"+q.encode()+"} b1="+b1+" b2="+b2+" c1="+c1+" c2="+c2+" factor="+f+" stops="+st+" "+note;p.edit().putString("enlargementDerivedRecipes",hist).putString("exposureRecipe",r.encode()).putString("printSequence",q.encode()).putInt("printWidthMs",nb).putString("enlargementMeta",nm).putString("enlargementLastLog",note).putBoolean("enlargementReloadPending",true).apply();Toast.makeText(this,"Ricetta derivata creata · tempi a 0,5 s",Toast.LENGTH_LONG).show();finish();}
}'''
(root/'EnlargementActivity.java').write_text(java,encoding='utf-8')
print('v017 polish applied')
