package it.darkroom.timer.assistant.development;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import java.util.Locale;

import it.darkroom.timer.assistant.chemistry.ChemistryCalculator;
import it.darkroom.timer.assistant.data.AssistantDatabase;

/** R4 result: source remains visible; personal/log time is explicit and separate. */
public final class DevelopmentResultActivity extends Activity {
    private int primary, muted, border, card, accent;
    private Bundle e;
    private AssistantDatabase db;
    private int activeSeconds;
    private String activeOrigin="FONTE / CALCOLO";
    private AssistantDatabase.PersonalRecipe preferred;
    private AssistantDatabase.PersonalRecipe latestPersonal;

    @Override protected void onCreate(Bundle savedInstanceState){ super.onCreate(savedInstanceState); palette(); db=new AssistantDatabase(this); e=getIntent().getExtras(); if(e==null){finish();return;} chooseActiveTime(); buildUi(); }
    @Override protected void onDestroy(){ if(db!=null)db.close(); super.onDestroy(); }

    private void palette(){boolean dark=getSharedPreferences("ui",MODE_PRIVATE).getBoolean("darkroomMode",false);if(dark){primary=Color.rgb(255,42,42);muted=Color.rgb(145,34,34);border=Color.rgb(112,20,20);card=Color.rgb(18,0,0);accent=Color.rgb(255,42,42);}else{primary=Color.rgb(238,240,242);muted=Color.rgb(145,151,158);border=Color.rgb(60,64,70);card=Color.rgb(24,26,30);accent=Color.rgb(197,54,58);}}
    private AssistantDatabase.SourceSnapshot snapshot(){AssistantDatabase.SourceSnapshot s=new AssistantDatabase.SourceSnapshot();s.film=e.getString("film","");s.format=e.getString("format","");s.nominalIso=e.getInt("nominalIso");s.exposedIso=e.getInt("exposedIso");s.developer=e.getString("developer","");s.dilution=e.getString("dilution","");s.originalTemp=e.getDouble("temperature");s.originalSeconds=e.getInt("seconds");s.sourceName=e.getString("source","");s.dataType=e.getString("dataType","");s.sourceData=e.getString("sourceData","");s.calculation=e.getString("calculation","");return s;}
    private void chooseActiveTime(){AssistantDatabase.SourceSnapshot s=snapshot();preferred=db.findPreferred(s.comboKey());latestPersonal=db.findLatest(s.comboKey());int repeat=e.getInt("repeatTimeSeconds",0);if(repeat>0){activeSeconds=repeat;activeOrigin=e.getString("repeatOrigin","RICETTA DAL LOG");return;}if(preferred!=null&&AssistantDatabase.sameTemperature(preferred.personalTemp,s.originalTemp)){activeSeconds=preferred.personalSeconds;activeOrigin="RICETTA PREFERITA";}else if(latestPersonal!=null&&AssistantDatabase.sameTemperature(latestPersonal.personalTemp,s.originalTemp)){activeSeconds=latestPersonal.personalSeconds;activeOrigin="MIA RICETTA";}else{activeSeconds=s.originalSeconds;activeOrigin=s.dataType.contains("ADATTATO")?"ADATTATO / CALCOLATO":"FONTE";}}

    private void buildUi(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(Color.BLACK);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(28));scroll.addView(root);
        TextView film=text(e.getString("film",""),25,primary,true);film.setGravity(Gravity.CENTER);root.addView(film);TextView l1=text(e.getString("format","")+" · ISO "+e.getInt("exposedIso"),15,muted,true);l1.setGravity(Gravity.CENTER);root.addView(l1);TextView chem=text(e.getString("developer","")+" · "+e.getString("dilution",""),17,primary,true);chem.setGravity(Gravity.CENTER);chem.setPadding(0,dp(14),0,dp(3));root.addView(chem);TextView temp=text(String.format(Locale.ITALY,"%.1f °C",e.getDouble("temperature")),16,primary,false);temp.setGravity(Gravity.CENTER);root.addView(temp);TextView proc=text("JOBO CPE2 · rotazione continua",15,accent,true);proc.setGravity(Gravity.CENTER);proc.setPadding(0,dp(5),0,dp(14));root.addView(proc);
        renderPersonalHint(root);
        TextView label=text("TEMPO DA IMPOSTARE SUL TIMER",12,muted,true);label.setGravity(Gravity.CENTER);root.addView(label);TextView time=text(DevelopmentCatalog.formatTime(activeSeconds),38,accent,true);time.setGravity(Gravity.CENTER);root.addView(time);TextView origin=text("Origine tempo: "+activeOrigin,12,muted,true);origin.setGravity(Gravity.CENTER);origin.setPadding(0,0,0,dp(15));root.addView(origin);
        LinearLayout prepare=new LinearLayout(this);prepare.setOrientation(LinearLayout.VERTICAL);prepare.setPadding(dp(14),dp(12),dp(14),dp(12));prepare.setBackground(roundRect(card,10,1,accent));root.addView(prepare);renderPrepare(prepare,e.getDouble("volumeMl",0));
        String tankPlan=e.getString("tankPlanSummary",""); if(tankPlan!=null&&!tankPlan.trim().isEmpty()){LinearLayout tankBox=new LinearLayout(this);tankBox.setOrientation(LinearLayout.VERTICAL);tankBox.setPadding(dp(14),dp(12),dp(14),dp(12));tankBox.setBackground(roundRect(card,10,1,border));tankBox.addView(text("TANK / PIANO CICLI",12,accent,true));tankBox.addView(text(tankPlan,12,primary,false));root.addView(tankBox,margin(-1,-2,0,8,0,0));}
        LinearLayout source=new LinearLayout(this);source.setOrientation(LinearLayout.VERTICAL);source.setPadding(dp(14),dp(12),dp(14),dp(12));source.setBackground(roundRect(card,10,1,border));source.addView(text("ORIGINALE FONTE",12,accent,true));source.addView(text("Tempo: "+DevelopmentCatalog.formatTime(e.getInt("seconds"))+" @ "+fmt(e.getDouble("temperature"))+" °C",13,primary,true));source.addView(text("Fonte: "+e.getString("source",""),12,primary,true));source.addView(text("Tipo dato: "+e.getString("dataType",""),12,accent,true));source.addView(text("Dato sorgente: "+e.getString("sourceData",""),11,muted,false));source.addView(text(e.getString("calculation",""),11,muted,false));root.addView(source,margin(-1,-2,0,12,0,0));
        String alt=e.getString("alternatives","");if(alt!=null&&!alt.trim().isEmpty()){Button b=button("ALTRE FONTI");TextView a=text(alt,11,muted,false);a.setVisibility(View.GONE);b.setOnClickListener(v->a.setVisibility(a.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));root.addView(b);root.addView(a);}
        Button saveRecipe=button("SALVA COME MIA RICETTA");saveRecipe.setOnClickListener(v->saveRecipeDialog());root.addView(saveRecipe,margin(-1,dp(54),0,dp(12),0,0));Button saveLog=button("SALVA SVILUPPO NEL LOG");saveLog.setOnClickListener(v->saveLogDialog());root.addView(saveLog,margin(-1,dp(54),0,dp(8),0,0));Button back=button("← MODIFICA SVILUPPO");back.setOnClickListener(v->finish());root.addView(back,margin(-1,dp(54),0,dp(12),0,0));setContentView(scroll);}

    private void renderPersonalHint(LinearLayout root){AssistantDatabase.SourceSnapshot s=snapshot();AssistantDatabase.PersonalRecipe p=preferred!=null?preferred:latestPersonal;if(p==null)return;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(10),dp(12),dp(10));box.setBackground(roundRect(card,9,1,border));if(p.favorite)box.addView(text("MIA RICETTA PREFERITA",12,accent,true));else box.addView(text("MIA RICETTA",12,accent,true));if(AssistantDatabase.sameTemperature(p.personalTemp,s.originalTemp)){box.addView(text(DevelopmentCatalog.formatTime(p.personalSeconds)+" @ "+fmt(p.personalTemp)+" °C"+(p.favorite?" · proposta":""),15,primary,true));}else{box.addView(text("Hai una ricetta personale salvata a "+fmt(p.personalTemp)+" °C: "+DevelopmentCatalog.formatTime(p.personalSeconds),13,primary,true));box.addView(text("Temperatura attuale "+fmt(s.originalTemp)+" °C: nessuna trasformazione automatica della ricetta personale.",11,muted,false));}root.addView(box,margin(-1,-2,0,0,0,dp(14)));}

    private void saveRecipeDialog(){LinearLayout box=formBox();EditText time=field("Tempo m:ss");time.setText(timeText(activeSeconds));EditText temp=field("Temperatura di riferimento °C");temp.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);temp.setText(fmt(e.getDouble("temperature")));EditText note=field("Nota personale");CheckBox fav=new CheckBox(this);fav.setText("PREFERITA");fav.setTextColor(primary);box.addView(time);box.addView(temp);box.addView(note);box.addView(fav);new AlertDialog.Builder(this).setTitle("SALVA COME MIA RICETTA").setMessage("L’ORIGINALE FONTE resterà immutabile.").setView(box).setPositiveButton("SALVA",(d,w)->{int sec=parseTime(time.getText().toString());double tc=parseDouble(temp.getText().toString());if(sec<=0||Double.isNaN(tc)){toast("Tempo o temperatura non validi");return;}db.saveRecipe(snapshot(),sec,tc,note.getText().toString(),fav.isChecked());toast("Ricetta personale salvata");e.putInt("repeatTimeSeconds",0);chooseActiveTime();buildUi();}).setNegativeButton("ANNULLA",null).show();}

    private void saveLogDialog(){LinearLayout box=formBox();EditText time=field("TEMPO EFFETTIVO m:ss");time.setText(timeText(activeSeconds));Spinner rating=new Spinner(this);String[] vals={"1 ★","2 ★★","3 ★★★","4 ★★★★","5 ★★★★★"};rating.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,vals));rating.setSelection(4);EditText notes=field("NOTE (opzionali)");box.addView(time);box.addView(rating);box.addView(notes);new AlertDialog.Builder(this).setTitle("SALVA SVILUPPO NEL LOG").setMessage("Il Log salva uno snapshot storico. Modificare il tempo qui non cambia la ricetta.").setView(box).setPositiveButton("SALVA",(d,w)->{int actual=parseTime(time.getText().toString());if(actual<=0){toast("Tempo effettivo non valido");return;}ChemistryCalculator.Result c=ChemistryCalculator.calculate(e.getString("developer",""),e.getString("dilution",""),e.getDouble("volumeMl",0),e.getString("format","120"),e.getInt("rolls",1));AssistantDatabase.LogEntry l=new AssistantDatabase.LogEntry();l.source=snapshot();l.actualTemp=e.getDouble("temperature");l.actualSeconds=actual;l.timeOrigin=activeOrigin;l.volumeMl=e.getDouble("volumeMl",0);l.productMl=c.dilutionKnown?c.productMl:0;l.waterMl=c.dilutionKnown?c.waterMl:0;l.productKnown=c.dilutionKnown;l.waterKnown=c.dilutionKnown;l.rolls=e.getInt("rolls",1);l.capacityState=c.capacityState;l.capacityMessage=c.capacityMessage;l.rating=rating.getSelectedItemPosition()+1;l.notes=notes.getText().toString();long logId=db.saveLog(l);toast("Sviluppo salvato nel Log");maybeRegisterChemicalUsage(logId,l,c);}).setNegativeButton("ANNULLA",null).show();}

    private void maybeRegisterChemicalUsage(long logId, AssistantDatabase.LogEntry l, ChemistryCalculator.Result c){
        AssistantDatabase.ChemicalItem item=db.findChemicalForDeveloper(l.source.developer); if(item==null)return;
        boolean ml="ml".equalsIgnoreCase(item.unit); boolean liters="litri".equalsIgnoreCase(item.unit)||"l".equalsIgnoreCase(item.unit);
        if(c.dilutionKnown&&(ml||liters)){
            final double used=liters?c.productMl/1000.0:c.productMl; final double after=Math.max(0,item.remainingAmount-used);
            String msg="Prodotto: "+item.name+"\nQuantità utilizzata: "+fmtAmount(used)+" "+item.unit+"\nResidua prima: "+fmtAmount(item.remainingAmount)+" "+item.unit+"\nResidua dopo: "+fmtAmount(after)+" "+item.unit+"\n\nLa sottrazione avverrà solo confermando.";
            new AlertDialog.Builder(this).setTitle("REGISTRA UTILIZZO CHIMICA").setMessage(msg).setPositiveButton("CONFERMA",(d,w)->{db.registerChemicalUsage(item.id,logId,used,item.unit,l,"");toast("Utilizzo chimica registrato");}).setNegativeButton("NON REGISTRARE",null).show();
        }else{
            LinearLayout box=formBox(); EditText q=field("Quantità realmente utilizzata · "+item.unit); q.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); box.addView(q);
            String reason=c.dilutionKnown?"L'unità dell'inventario non è convertibile automaticamente.":"Quantità prodotto non determinata: la diluizione non è documentata.";
            new AlertDialog.Builder(this).setTitle("REGISTRA UTILIZZO CHIMICA").setMessage(reason+" Inserisci la quantità realmente usata oppure annulla: nulla verrà sottratto automaticamente.").setView(box).setPositiveButton("REGISTRA",(d,w)->{double used=parseDouble(q.getText().toString());if(Double.isNaN(used)||used<0){toast("Quantità non valida");return;}db.registerChemicalUsage(item.id,logId,used,item.unit,l,"Quantità inserita manualmente");toast("Utilizzo chimica registrato");}).setNegativeButton("NON REGISTRARE",null).show();
        }
    }
    private static String fmtAmount(double v){return Math.abs(v-Math.rint(v))<0.05?String.format(Locale.ITALY,"%.0f",v):String.format(Locale.ITALY,"%.2f",v);}

    private void renderPrepare(LinearLayout box,double volume){box.removeAllViews();int rolls=e.getInt("rolls",1);String format=e.getString("format","120"),developer=e.getString("developer",""),dil=e.getString("dilution","");ChemistryCalculator.Result p=ChemistryCalculator.calculate(developer,dil,volume,format,rolls);box.addView(text("PREPARA",12,accent,true));box.addView(text(developer+" "+dil,16,primary,true));if(!p.inputValid){box.addView(text(p.error,12,accent,true));return;}if(p.dilutionKnown){box.addView(text(ChemistryCalculator.formatMl(p.productMl)+" ml prodotto / stock",16,primary,true));box.addView(text(ChemistryCalculator.formatMl(p.waterMl)+" ml acqua",16,primary,true));box.addView(text(ChemistryCalculator.formatMl(p.totalMl)+" ml totale",16,primary,true));}else box.addView(text(p.dilutionMessage,12,accent,true));box.addView(text(rolls+" × "+format,12,muted,true));box.addView(text(p.capacityMessage,12,ChemistryCalculator.CAPACITY_INSUFFICIENT.equals(p.capacityState)?accent:muted,false));if(p.canAdoptMinimum){Button adopt=button("USA VOLUME MINIMO · "+ChemistryCalculator.formatMl(p.minimumVolumeMl)+" ml");adopt.setOnClickListener(v->{e.putDouble("volumeMl",p.minimumVolumeMl);renderPrepare(box,p.minimumVolumeMl);});box.addView(adopt);}}

    public static int parseTime(String s){try{String x=s.trim();if(x.contains(":")){String[] p=x.split(":");return Integer.parseInt(p[0].trim())*60+Integer.parseInt(p[1].trim());}return Integer.parseInt(x);}catch(Exception ex){return-1;}}private static double parseDouble(String s){try{return Double.parseDouble(s.trim().replace(',','.'));}catch(Exception ex){return Double.NaN;}}private static String timeText(int s){return String.format(Locale.ITALY,"%d:%02d",s/60,s%60);}private static String fmt(double v){return String.format(Locale.ITALY,"%.1f",v);}private LinearLayout formBox(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(20),0,dp(20),0);return b;}private EditText field(String h){EditText x=new EditText(this);x.setHint(h);x.setHintTextColor(muted);x.setTextColor(primary);return x;}private Button button(String t){Button b=new Button(this);b.setText(t);b.setAllCaps(false);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(primary);return b;}private TextView text(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable roundRect(int c,int r,int sw,int sc){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));if(sw>0)d.setStroke(dp(sw),sc);return d;}private LinearLayout.LayoutParams margin(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
